# Generated by Django 2.2.10 on 2020-02-09 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def forward_func(apps, schema_editor):
    # 현재 모든 User에 대해서 Profile을 만들어줍니다.
    auth_user_model = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(*auth_user_model) # *은 python에서 packing & unpacking 매개변수, 여기서는 unpacking으로 사용
    Profile = apps.get_model('accounts', 'Profile')

    for user in User.objects.all():
        print('create profile for user #{}'.format(user.pk))
        Profile.objects.create(user=user) # models.py에서 필수 입력값이 user밖에 없기 때문임

def backward_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(forward_func, backward_func), # migrate되어 DB에 table이 생성되자 마자 forward_func와 backward_func을 실행시킴
    ]
